# Generated by Django 5.0 on 2023-12-19 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='Date',
            new_name='date',
        ),
    ]
