# Generated by Django 5.0 on 2023-12-19 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingspace', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='check_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='parking_status',
            field=models.BooleanField(default=True),
        ),
    ]
