# Generated by Django 5.0 on 2023-12-19 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingspace', '0003_parking_check_out_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='parking_time',
            field=models.DateTimeField(),
        ),
    ]
