# Generated by Django 5.0 on 2024-04-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkingspace', '0004_alter_parking_parking_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingprice',
            name='four_wheeler_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
